graph TD
ad3e129["dir1/file.txt , dir2/dasdsadasdas.txt , test.txt"]
c05996b["dasdadas/dasdsadasdas.txt , dir1/file.txt , dir2/dasdsadasdas.txt"]
36278b4["dasdadas/dasdsadasdas.txt , test.txt"]
29399b6["dasdadas/dasdsadasdas.txt , test.txt"]
5617d0b["test.txt"]
ad3e129 --> c05996b
c05996b --> 36278b4
36278b4 --> 29399b6
29399b6 --> 5617d0b
5617d0b --> 74bb544